/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "header.h"

void delay(volatile uint32_t count)
{
    while(count--);
}
void GPIO_INIT()
{
	RCC_AHB1ENR |= (1 << 1);
	GPIOB_MODER &=~(3<<28);
	GPIOB_MODER |=(1<<28);
}

int main(void){
	GPIO_INIT();

	while(1)
	{
		GPIOB_ODR |=(1<<14);
		delay(10000);
		GPIOB_ODR &=~(1<<14);
		delay(10000);

	}

}


